import Home from './home';
import LogIn from './login';
import SignUp from './sign-up';
import ForgotPass from './forgot-pass';
import Onboarding from './onboarding';
import Splash from './splash';
import Search from './search';
import Order from './order';
import User from './user';
import Otp from './otp';
import Notification from './notification';
import NotificationDetail from './notification-detail';
import ServiceDetail from './detail-service';
export {Home, LogIn, Onboarding, Splash, Search, Order, User, Notification, NotificationDetail, ServiceDetail, SignUp, ForgotPass, Otp};
