import {FirebaseAuthTypes} from '@react-native-firebase/auth';
import {NotificationItemProps, OrderProps, ServiceProps} from '../constants/types';
import {UserProps} from '../constants/types';

export type RootStackScreensParams = {
	Splash: undefined;
	LogIn: undefined;
	Onboarding: undefined;
	Home: undefined;
	Search: undefined;
	ServiceDetail: {serviceData: ServiceProps};
	NotificationDetail: {notificationData: NotificationItemProps};
	Notification: undefined;
	SignUp: undefined;
	SignUpServices: undefined;
	ForgotPass: undefined;
	Otp: {confirm: FirebaseAuthTypes.ConfirmationResult; userPhone: UserProps};
	ChangePasswordForgot: {userPhone: UserProps};
	BottomTab: undefined;
	Order: undefined;
	User: undefined;
	UpdateInformation: undefined;
	Booking: {service: ServiceProps};
	Setting: undefined;
	FAQs: undefined;
	Privacypolicy: undefined;
	Termsandconditions: undefined;
	ChangePassword: undefined;
	ListAddress: undefined;
	DetailOrder: {data: OrderProps};
	Payment: undefined;
};
