export const VI = {
	BottomTab: {
		logoutAlert: 'Tài khoản của bạn đã bị chặn!',
		logoutAlertReason: (reasonBlock: string) => `Lí do ${reasonBlock}`,
	},
	Onboarding: {},
	Home: {
		title: 'TRANG CHỦ',
		Listofservices: "Danh mục dịch vụ",
	},
	Notification: {},
	Order: {},
	User: {
		title: 'HỒ SƠ',
		activityStatusText: 'Trạng thái hoạt động',
		updateInfoButtonText: 'Cập nhật thông tin',
		addressButtonText: 'Địa chỉ',
		changePasswordButtonText: 'Đổi mật khẩu',
		feeServiceText: 'Phí dịch vụ: ',
		blockedUsersButtonText: 'Danh sách người dùng bị chặn',
		otherInfoText: 'THÔNG TIN KHÁC',
		termsButtonText: 'Quy định điều khoản',
		privacyPolicyButtonText: 'Chính sách quyền riêng tư',
		faqsButtonText: 'FAQs',
		settingsButtonText: 'Cài đặt',
		logoutButtonText: 'Đăng xuất',
		logoutConfirmationMessage: 'Bạn chắc chắn muốn đăng xuất?',
		unpaid: 'Chưa thanh toán',
		paid: 'Đã thanh toán',
		wait: 'Chờ sét duyệt',
		ACCOUNT_MANAGEMENT: 'QUẢN LÝ TÀI KHOẢN',
		SERVICE: 'DỊCH VỤ',
	},
	Search: {},
	DetailService: {},
	Booking: {},
	InfoServicer: {},
	AllReview: {},
	DetailNotification: {},
	ChangePassword: {},
	Setting: {
		title: 'CÀI ĐẶT',
		listLanguage: ['Việt Nam', 'Tiếng Anh', 'Tiếng Trung', 'Tiếng Nhật', 'Tiếng Hàn'],
		Language: 'Ngôn ngữ',
	},
	Term: {},
	UpdateInformation: {
		title: 'CẬP NHẬP THÔNG TIN',
		fullname: 'HỌ VÀ TÊN',
		phonenumber: 'SỐ ĐIỆN THOẠI',
	},
	ListAddress: {},
	ChangePasswordForgot: {},
	DetailOrder: {},
	AddService: {},
	AcceptServicer: {},
	InfoAcceptServicer: {},
	ManageServicer: {},
	InfoDetailServicer: {},
	ManageUser: {},
	InfoDetailUser: {},
	AddCategory: {},
	AddServiceCategory: {},
	Payment: {},
	EditPaymentFee: {},
	AddPayment: {},
	EvaluateService: {},
	ListUserBlock: {},
	FeeService: {},
	ManagePayment: {},
	AddressServicer: {},
	Policy: {},
	FAQ: {},
};
